### ISSUE TITLE
Handling errors without stacks

### ISSUE THREAD

**Issue by SEAPUNK** [sindresorhus/aggregate-error#1]
Ref: https://github.com/sindresorhus/clean-stack/issues/1

**Comment by sindresorhus** [comment]
I don't really see how that's helpful. An error without a stack is an invalid error. But more importantly, you have no idea where it came from. I don't think it's a good idea to silently handle invalid errors. Better to have it throw here IMHO.

**Comment by SEAPUNK** [comment]
Yeah, makes sense. I'm not even sure how that kind of error can even happen in the first place.

I made a module to work around it in the meantime -- [guaranteed-error](https://github.com/SEAPUNK/guaranteed-error)
