### ISSUE TITLE
question[TypeScript] How should AggregateError be imported as type when using TypeScript without esModuleInterop option

### ISSUE THREAD

**Issue by oscard0m** [sindresorhus/aggregate-error#14]
When trying to use `AggregateError` as type in a Typescript project the following issue happens:
![image](https://user-images.githubusercontent.com/2574275/93539833-29138100-f952-11ea-8f4e-bdf955636835.png)

### Conditions
* To not use `esModuleInterop` in `tsconfig.json`

### Tried alternatives
![image](https://user-images.githubusercontent.com/2574275/93539852-3af52400-f952-11ea-9f60-58f8ca18ef49.png)
(this would not fit the purpose of getting the `type`)

---

![image](https://user-images.githubusercontent.com/2574275/93539899-552f0200-f952-11ea-88c9-2b25af0a0e68.png)
(it implies enabling `moduleInterop` flag)

---

![image](https://user-images.githubusercontent.com/2574275/93539958-84457380-f952-11ea-9641-80b948fd5999.png)

### Question
Considering the way this library is exposing AggregateError, Is there a way to import `AggregateError` in a ESModule way **as Typescript type** (so, no `const AggreagateError = require('aggregate-error')` and without enabling `esModuleInterop` option?

### Details
You can find more details in:
* https://github.com/octokit/webhooks.js/pull/248/files
* https://github.com/octokit/webhooks.js/issues/245

**Comment by sindresorhus** [comment]
This is not the place to ask for general TypeScript support.

**Comment by sindresorhus** [comment]
> Considering the way this library is exposing AggregateError, Is there a way to import AggregateError in a ESModule way as Typescript type (so, no const AggreagateError = require('aggregate-error') and without enabling esModuleInterop option?

I don't think that's possible, no. That is indeed a weird limitation though. I would have expected `import type AggreagateError = require('aggregate-error')` to work. I would bring this up with the TS team.

**Comment by oscard0m** [comment]
> > Considering the way this library is exposing AggregateError, Is there a way to import AggregateError in a ESModule way as Typescript type (so, no const AggreagateError = require('aggregate-error') and without enabling esModuleInterop option?
> 
> I don't think that's possible, no. That is indeed a weird limitation though. I would have expected `import type AggreagateError = require('aggregate-error')` to work. I would bring this up with the TS team.

You are totally right. Sorry for "spamming" issues here. I will address this question to the proper TypeScript channel.

Thanks for your attention and support ❤️

**Comment by gr2m** [comment]
@sindresorhus the current CommonJS-style export makes `aggregate-error` hard to consume for ES Module-style libraries such as all the `@octokit/*` modules. Every consumer of e.g. `@octokit/webhooks` will have to add `skipLibCheck: true` to their TSConfig settings, there is nothing on our side that we can do.

A workaround was kindly suggested by @smockle via https://github.com/smockle/aggregate-error-test/: but it requires us to override `aggregate-error`'s type definitions, which puts the burden on us to keep it up-to-date with the implementation.

I understand the change was done here: https://github.com/sindresorhus/aggregate-error/pull/9 which I think references https://github.com/sindresorhus/p-cancelable/pull/19, but I don't see the reason why you decided to make that change? Is there a discussion somewhere that I can learn more about your reasoning?

**Comment by gr2m** [comment]
Update: I've found https://github.com/sindresorhus/mem/issues/31#issuecomment-475850181 (thanks @smockle)
