### ISSUE TITLE
Use native AggregateError if available

### ISSUE THREAD

**Issue by mk-pmb** [sindresorhus/aggregate-error#18]
I see the hint in the readme that modern node has it, but I don't see feature detection code in `index.js` and

```text
$ node -e 'import("aggregate-error").then(({ default: AE }) => console.log({
>   v: process.versions.node, AE, AggregateError, same: AE === AggregateError}))'
{
  v: '16.14.0',
  AE: [class AggregateError extends Error],
  AggregateError: [Function: AggregateError],
  same: false
}
```

**Comment by sindresorhus** [comment]
I don't intend to make this package a polyfill. There are many differences between this and the native one. I personally plan to move to the native API when I can target Node.js 16 in my packages that use this package.
