### ISSUE TITLE
Tests are failing on master

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/aggregate-error#2]
```
> npm test

> aggregate-error@1.0.0 test /Users/felix/git/aggregate-error
> xo && ava


  index.js:20:15
  ✖  20:15  The name property should be set to AggregateError.  unicorn/custom-error-definition

  1 error
npm ERR! Test failed.  See above for more details.
```

`xo` is failing, seems a bit dangerous to depend on `xo@*`?

**Comment by sindresorhus** [comment]
I have it to `*` so I can be a beta tester of AVA and XO on all my modules. Better me running into bugs on new releases than my users. I usually update all my modules when new XO releases are out, but I have to admit I've been a bit slow at doing it this time.

**Comment by felixfbecker** [comment]
Have you considered using Greenkeeper or Renovate for that purpose?

Merry Christmas!
