### ISSUE TITLE
Thoughts on requiring Node 14?

### ISSUE THREAD

**Issue by manzt** [sindresorhus/aggregate-error#21]
Thank you for all your open-source work.

I'm a user of `p-*` libraries, and it would be great to have the improved browser support implemented in the latest `clean-stack` (https://github.com/sindresorhus/clean-stack/commit/dccdb49b3215ffb78b962e578be9e7cf87eb1ace). From what I can tell, the braking changes in `clean-stack` v5 relate to node requirements.

I'm happy to open a PR, but wanted to ask if there is perhaps some reason to keep Node 12 support in this library.

**Comment by sindresorhus** [comment]
I plan to drop this package and use native `AggregateError` in April (when I can target Node.js 16).

**Comment by manzt** [comment]
Ok! Thanks.
