### ISSUE TITLE
message generation breaks when AbortError/Error without stack is encountered

### ISSUE THREAD

**Issue by kmohrf** [sindresorhus/aggregate-error#6]
Hi,

I’m not quite sure if this is a bug that should be handled here or in the clean-stack lib, but when using abortable fetch requests on ArchLinux with Chromium 72.0.3626.96 a `DOMException`/`AbortError` is thrown that, even though it is an instance of `Error`, does not have a stack (it’s simply `undefined`). I’ve yet to confirm if this is standard-compliant and/or happens in other browsers but for the sake of being robust I think it would be a good idea to actually check if `err.stack` exists during the generation of `message`.

Example ([bundled version](https://github.com/sindresorhus/aggregate-error/files/2866033/stack_error.zip)):

```js
import AggregateError from 'aggregate-error'

const { fetch, AbortController } = window
const controller = new AbortController()
const signal = controller.signal

fetch('https://api.github.com/', { signal })
  .then(res => res.json())
  .then(data => { console.info(data) })
  .catch(err => Promise.reject(new AggregateError([new Error('something went south during github api request'), err]))

controller.abort()
```
cheers Konrad

**Comment by kmohrf** [comment]
I can confirm that the `AbortError` in Firefox 65 does have a stack and therefore works with this library. Still a missing stack should be handled gracefully.

**Comment by kmohrf** [comment]
I just saw that #1 already tackled this issue. In case you don’t change your mind feel free to close this but in the light that even major browsers seem to have a loose definition of a valid `Error` instance, you might want to reconsider.

Whatever you do: thank you for your time.

**Comment by sindresorhus** [comment]
Alright. PR welcome.

**Comment by kmohrf** [comment]
there you go :)
